### ISSUE TITLE
Non-HTTP Proxy settings do not persist

### ISSUE THREAD

**Issue by cybergibbons** [summitt/Burp-Non-HTTP-Extension#1]
I am not sure if this is a bug or missing functionality, but the Non-HTTP Proxy settings do not persist when Burp is closed and re-opened.

Java JRE:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Burp 1.7.05

**Comment by summitt** [comment]
Currently they are not saved with the project. This will be added in the
future.

Thanks
Josh

**Comment by cybergibbons** [comment]
Thanks.
