### ISSUE TITLE
Non-HTTP Proxy Listeners

### ISSUE THREAD

**Issue by ifrane** [summitt/Burp-Non-HTTP-Extension#13]
It seems that the extension has issues with enabling more than 2 listeners to the to the non-proxy options under server config. I can add numerous non-http proxy listeners, but i can only enable 2 (rarely 3).

If i click on the enable checkbox, nothing happens. It does select the row, but the checkbox does not become enabled.

**Comment by ifrane** [comment]
Nope wasn't trying to enable more than one per port. 

But I noticed that if I added/removed or enabled/disabled the non-http proxies several times it would freeze the proxy area so I wouldn't be able to make any further changes. i would have to either remove the extension or close and open burp to get control again.

**Comment by summitt** [comment]
yay. bugs. i'll test and see if i can reproduce. what OS are you testing.

**Comment by summitt** [comment]
are you using the most recent version with the colored icons?

**Comment by ifrane** [comment]
Yup, the most recent with coloured icons.

Windows 8.1 Enterprise 64bit with java 1.8.0_111, I have not tried it with
my Kali OS
