### ISSUE TITLE
error while adding to burp 

### ISSUE THREAD

**Issue by ahmed-reda2100** [summitt/Burp-Non-HTTP-Extension#14]
when i try to add it to burp i get the following error:

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2271)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
	at burp.iud.a(Unknown Source)
	at burp.mlf.<init>(Unknown Source)
	at burp.bld.a(Unknown Source)
	at burp.u1b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:722)

i tried to start burp with following option but i get the same error:
 java -XX:MaxPermSize=1G -jar burp.jar

**Comment by summitt** [comment]
Try running it like:

java -Xmx1G -jar burp.jar

and let me know if you still see the problem.

I actually unusually give burp at least 3 to 6 gigs but that's mostly for
scanning.

Thanks
Josh

**Comment by summitt** [comment]
Also let me know the OS your running if you still have issues.

**Comment by ahmed-reda2100** [comment]
Thanks for your help, i changed my OS to windows and i can upload it now

i made all configuration as the following screen shots, but i still can not see any TCP history, please help 
![screenshot_1](https://cloud.githubusercontent.com/assets/25224857/22203125/26372bde-e174-11e6-97d7-05042e4b45e8.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/25224857/22203126/263b702c-e174-11e6-9d8f-70e7305226a6.jpg)

**Comment by summitt** [comment]
the first thing i notice is that you have not checked 'Use the above DNS
Response IP....'. If you use that setting then you need to add an entry to
the custom host field below otherwise everything will resolve to the real
ip address.

second i notice the unresolved DNS messages. By default the tool uses
8.8.8.8 to resolve hostnames. You may not be able to access this server on
your internal network. You can change this as described here:
https://github.com/summitt/Burp-Non-HTTP-Extension/wiki/Advanced-DNS-config

Third try creating your listener without ssl. this way you can see if its
at least connecting through Nope and we can debug SSL issues later if
that's the problem.

let me know if any of this helps.

**Comment by ahmed-reda2100** [comment]
Thanks for your replay. After i checked 'Use the above DNS
Response IP....' and adding the server's address and hostname to the Custom Hosts file it's working now and i can see all TCP traffic. but the traffic is encrypted as my app use SSL.

When i try to create SSL listener by following these steps https://github.com/summitt/Burp-Non-HTTP-Extension/wiki/Intercepting-SSL-Traffic-with-NoPE  my application could not reach the server again.

how i can solve this please

**Comment by Sikkandar-Sha** [comment]
Hi,

I am unable to add this extension to Burp. When I add the BurpExtender.java from the src folder to the extender in burp, I get the below error.

java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.rt.a(Unknown Source)
	at burp.rt.<init>(Unknown Source)
	at burp.pxf.a(Unknown Source)
	at burp.wke.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sikkandar-Sha** [comment]
I have also tried this 

java -Xmx1G -jar burp.jar

**Comment by ahmed-reda2100** [comment]
Hi Sikkandar-Sha,

You need to upload NopeProxy.jar file you can download it form the following link:
https://github.com/summitt/Burp-Non-HTTP-Extension/releases
