### ISSUE TITLE
SOCKS Support

### ISSUE THREAD

**Issue by unashamedgeek** [summitt/Burp-Non-HTTP-Extension#16]
First off, this is an amazing extension. One feature that would be useful is if it supported the SOCKS Proxy option in Burp. I currently have a SOCKS Proxy set up, but monitoring my traffic shows that the NoPE Proxy is sending traffic directly from my host to the server without using the SOCKS Proxy.

Thanks again for this.

**Comment by summitt** [comment]
Currently the extension does no support any upstream proxy settings. if
your on a mac you can try setting the socks proxy option in network
settings. not sure if there is a similar global option in windows.
