### ISSUE TITLE
extension dosent support my burp suite 

### ISSUE THREAD

**Issue by Expertasif** [summitt/Burp-Non-HTTP-Extension#18]
![java](https://cloud.githubusercontent.com/assets/16167241/26751050/2b190c30-484e-11e7-8cc3-1ad852d60dfa.PNG)

**Comment by ptr0x01** [comment]
Start burp by allocating more memory to it, e.g. this launches it with 2Gigs of RAM.

java -jar -Xmx2G /path/to/burp.jar

**Comment by LockGit** [comment]
wonderful

**Comment by Expertasif** [comment]
hey peter,

peter your nopehttp extension not working in my burp suite can you provide
me step by step installation

thanks

cheers

Asif

**Comment by z977780633** [comment]
The program stops when the proxy setting is removed

**Comment by summitt** [comment]
@z977780633 There is a bug in the current table settings. This happens sometimes but not all the time. This has been mitigated in the version i'm currently testing now. I should push an update in the next few days.
