### ISSUE TITLE
am i right for ssl ?

### ISSUE THREAD

**Issue by duolaaa** [summitt/Burp-Non-HTTP-Extension#19]
Hi,Josh summitt, when i use Burp-Non-HTTP-Extension as the wiki
**Basic Set Up for mobile testing**. (testing on two machines)  ,everything works fine but for ssl .
and i have already installed burpCA in my iphone ,and trust it . when i use iphone view http ,it work,but don not work for https .Looking forward to your reply.

**Comment by summitt** [comment]
A few quick questions to be sure we are on the same page. 
1) Have you exported burp's ca cert into the same folder that contains the burpsuite.jar  ?
2) Have you checked the SSL box before starting the listener?
3) Does your domain name have non-ascii/international characters?
4) Ensure that your **Certificate HostName** does not have any spaces before or after.

**Comment by duolaaa** [comment]
it's late for reply, thank your so much Josh summitt . you can close this issue.
