### ISSUE TITLE
Unable to enable or remove Non-HTTP proxies on occassion

### ISSUE THREAD

**Issue by cybergibbons** [summitt/Burp-Non-HTTP-Extension#2]
The list of Non-HTTP proxies sometimes does not allow me to remove or enable proxies. A restart is required so that they can be added again.

Java JRE:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Burp 1.7.05

**Comment by summitt** [comment]
Did you see this bug when you created a SSL proxy and then tried to create
a non-SSL proxy? I have a known bug in there that i have yet to track down

Thanks
Josh

**Comment by cybergibbons** [comment]
Yes - that situation appears to trigger it. I am not sure if it happened in other situations. Glad you have noticed it though.

**Comment by osmooth** [comment]
Hi, please can you help ? I have two devices which connect using UDP on a local wifi network, can I use NoPE to intercept the traffic? I'm struggling to get this working between two clients one of which is a mobile app and the other a LIFX bulb.

**Comment by summitt** [comment]
I currently do not support UDP but its coming. Sorry.

**Comment by osmooth** [comment]
Appreciate your response. Thanks

**Comment by summitt** [comment]
@cybergibbons, this issue has been fixed in release 1.4.4 along with some other enhancements.
