### ISSUE TITLE
Failed to verify BApp file

### ISSUE THREAD

**Issue by admimistrator** [summitt/Burp-Non-HTTP-Extension#22]
manual install and it will show "Failed to verify BApp file" ???
![aaa](https://user-images.githubusercontent.com/9912143/36798525-db3d988a-1ce5-11e8-87b5-cfcad973effb.jpg)

**Comment by summitt** [comment]
How are importing it. Never seen this issue. What OS are you running.

**Comment by xuchaobei** [comment]
@summitt 
OS: OS X EI Capitan(10.111.6) 
Burp version: Burp Suite Community Edition v1.7.33
I choose the release Jar through manual install, then the error occurs.

**Comment by karan-a** [comment]
After adding it, where can I see the extension? It is not displaying anywhere

**Comment by caryhooper** [comment]
To be clear, the error was caused by @admimistrator was trying to add a custom Burp extension by navigating to Extender --> BApp Store --> Manual Install ...  To solve, go to Extender --> Extensions -->  Add.
