### ISSUE TITLE
No Support for Java 9 - 

### ISSUE THREAD

**Issue by stuartw1** [summitt/Burp-Non-HTTP-Extension#25]
The current version of  NoPE  (commit d9c7d51 ) does not appear to support oracle JDK / JRE 9 (tested 9.0.4). The extension loads in burp 1.7.32 but the NoPE tab does not display in the UI and no errors are displayed.

After lots of trial and error / troubleshooting I isolated the issue to the use of Java 9 (9.0.4). The issue does not occur when the current Java 8 (8u162) JRE is used 

Flagged as in issue to hopefully save others the time that I sunk into this today :)

**Comment by summitt** [comment]
Thanks for this info. I'll see if i can find what could be messing this up.

**Comment by stuartw1** [comment]
No worries - thanks for the good tool :)

Happy to provide further info if required
