### ISSUE TITLE
NOPE Proxy tab does not appear in Burp 2.0.16beta

### ISSUE THREAD

**Issue by 7a** [summitt/Burp-Non-HTTP-Extension#32]
Could you please investigate why the NOPE Proxy tab does *not* appear in Burp 2.0.16beta?
It used to appear in earlier betas such as Burp 2.0.8beta.

Thanks!

**Comment by NavjotSinghMinhas** [comment]
Do you have the link for Burp 2.0.8 Beta? :)

**Comment by 7a** [comment]
At this stage, it's no longer beta, please just make it work on the latest Burp version, thank you :)

**Comment by 1110001** [comment]
> At this stage, it's no longer beta, please just make it work on the latest Burp version, thank you :)

Did you get any solution? I am having the same issue.

**Comment by ilmanuz** [comment]
Chances are the issue is related to the jvm you use. I was in the same situation and I solved by explicitly launching burp with an older jvm (Java SE 8) than the one my system was picking by default. After that the nope tab re-appeared.

**Comment by summitt** [comment]
The changes have been merged from @jfish7 that mitigates this issue with newer versions of BURP
