### ISSUE TITLE
Issue with self signed certs for c2s communication? 

### ISSUE THREAD

**Issue by ColdHeat** [summitt/Burp-Non-HTTP-Extension#4]
Could be an issue with my setup but I'm not sure here. 

```
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at josh.nonHttp.GenericMiTMServer.Closed(GenericMiTMServer.java:434)
        at josh.nonHttp.SendData.SendClosedEventTrigger(SendData.java:81)
        at josh.nonHttp.SendData.run(SendData.java:317)
        at java.lang.Thread.run(Thread.java:745)
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by summitt** [comment]
Did you export burp's ca cert to burpca.p12 (password 'changeit') and store it in the same folder as your running burp instance before starting the SSL listener?

**Comment by ColdHeat** [comment]
Yes I did. 

It says No P12 file if it can't find it I believe.

**Comment by summitt** [comment]
I think i know what might be happening....

And just to confirm your folder structure should be like this:

```
/BURPPATH/burpsuite_pro_v1.7.04.jar
/BURPPATH/burpca.p12
```

and  you must run burp out of that folder like:
```
cd /BURPPATH/
java -jar ./burpsuite_pro_v1.7.04.jar
```

If you run burp like this then it can't find the cacert file. I should probably make this configurable:
`java -jar /BURPPATH/burpsuite_pro_v1.7.04.jar    ###This fails and can't find the ca cert`

**Comment by ColdHeat** [comment]
My folder structure does look like that and I am running the jar file like that. 

I still get this error:

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am able to see traffic from c2s but I don't see traffic from s2c. Perhaps my configuration is wrong but I am not seeing the a respective port in lister.py so it's just set to 443 and 443.

**Comment by summitt** [comment]
I'm really not sure. I've never seen a problem with one direction works but the other gives cert errors... The only thing i can think of is that the app your testing doesn't have burp's CA installed. 

I guess in theory if the server responses first when your connect then you would see the server-to-client response while the client is still failing to fully connect to NoPE due to cert issues. 

Is the app your testing something i could download and troubleshoot?

**Comment by summitt** [comment]
Hey, are you still having issues. If so email me at josh[dot]summitt[at]fusesoft[dot]co. Maybe if i can get some screenshots of your config something might jump out as to why its not working.
