### ISSUE TITLE
DNS server does not start on OSX Catalina

### ISSUE THREAD

**Issue by na-ji** [summitt/Burp-Non-HTTP-Extension#42]
Hello,

I am running Burp Suite as root on OSX Catalina. After starting the server on port 53, I could not get any data in the DNS history. After checking the currently used ports, I saw that there is not any app listening on this port. I tried changing the port to something else (like 5353) but still no app listening. I tried to run the Burp's proxy on this port, and it could listen on this port without problem, so I am pretty sure Burp does have every privileges needed. 

I am pretty new to using Burp suite, but I can add more information if you tell me what you need.

Thanks.

**Comment by summitt** [comment]
fixed in most recent release
