### ISSUE TITLE
doesn't respond to DNS requests

### ISSUE THREAD

**Issue by NelyusC** [summitt/Burp-Non-HTTP-Extension#43]
Hello,
From what I understand (tried to follow this https://github.com/summitt/Burp-Non-HTTP-Extension/wiki#basic-set-up-for-local-client-testing-on-a-single-machine) the extension should respond a DNS response from the Google DNS server (unless it is in the custom hosts file or unless the "use the above 'DNS...'" is checked.) but from what I seen it doesn't respond anything.

I am running burp on Windows.

Thanks!

**Comment by summitt** [comment]
This should be fixed in the most recent release
