### ISSUE TITLE
Got error on macos mojave when starting port monitor

### ISSUE THREAD

**Issue by zxy12** [summitt/Burp-Non-HTTP-Extension#44]
I got this error when tring to start port monitor

![image](https://user-images.githubusercontent.com/4112803/102092230-cd766800-3e5a-11eb-9ce9-7b7faca23d60.png)

and port monitor doesn't work, please help me fix this issue

**Comment by zxy12** [comment]
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11)
OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)

**Comment by zxy12** [comment]
extender: NoPE-v1.6.jar

**Comment by yoyo00xx** [comment]
I got the same issue any update on this on how you fixed it?

**Comment by yoyo00xx** [comment]
@zxy12

**Comment by zxy12** [comment]
> @zxy12

not yet

**Comment by summitt** [comment]
This should be fixed in NoPE 1.7.2.
