### ISSUE TITLE
port monitor doesn't work on mac

### ISSUE THREAD

**Issue by birdmanwings** [summitt/Burp-Non-HTTP-Extension#47]
mac:10.15
burp:burp suite community edition 2020.12.1
java:openjdk 11.0.9.1
I have already installed libpcap through brew install libpcap. And I can receive the dns history on the left window, but there is nothing on the right window(port monitor).Just like that: 
![](http://image.bdwms.com/FuM51RlaTa8_1-4hVb7dXHf0I7wZ) 
anyone has the same situation? please help me,thanks~

**Comment by Xumeiquer** [comment]
I am also getting a NullPointerException.

In my case, I am using the Oracle java version.
```sh
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

```sh
Lister Started
java.lang.NullPointerException: Cannot invoke "org.pcap4j.packet.TcpPacket.getHeader()" because "tcp" is null
	at josh.utils.Lister$1.gotPacket(Lister.java:70)
	at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.lambda$got_packet$0(PcapHandle.java:1254)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Lister Stopped
```

**Comment by cyal1** [comment]
> mac:10.15
> burp:burp suite community edition 2020.12.1
> java:openjdk 11.0.9.1
> I have already installed libpcap through brew install libpcap. And I can receive the dns history on the left window, but there is nothing on the right window(port monitor).Just like that:
> ![](https://camo.githubusercontent.com/8e147fd65444546d43e3dc76ab9d864eb07e1c1f4465b9b55a3307fb106726e2/687474703a2f2f696d6167652e6264776d732e636f6d2f46754d3531526c615461385f312d346856623764584866304937775a)
> anyone has the same situation? please help me,thanks~

I also encountered the same problem, did you solve this problem,

**Comment by birdmanwings** [comment]
> > mac:10.15
> > burp:burp suite community edition 2020.12.1
> > java:openjdk 11.0.9.1
> > I have already installed libpcap through brew install libpcap. And I can receive the dns history on the left window, but there is nothing on the right window(port monitor).Just like that:
> > ![](https://camo.githubusercontent.com/8e147fd65444546d43e3dc76ab9d864eb07e1c1f4465b9b55a3307fb106726e2/687474703a2f2f696d6167652e6264776d732e636f6d2f46754d3531526c615461385f312d346856623764584866304937775a)
> > anyone has the same situation? please help me,thanks~
> 
> I also encountered the same problem, did you solve this problem,

not yet, but I succeed to use another tool (sslsplit) to decrypt ssl.

**Comment by indianajson** [comment]
This is still an issue for current installations and makes the plug-in difficult to use without an additional tool to identify the port.

**Comment by fkerem** [comment]
Can confirm that it is still not working for Mac.

**Comment by summitt** [comment]
A fix for this has been pushed [here](https://github.com/summitt/Burp-Non-HTTP-Extension/commit/2c2e1830ec8fec772bf4ee62c34ae35588a6ac6e#diff-5ab9fac41fd253f8b75152a9a8c57f8fa114e4b6844fcfe1e4f5a685b48f2d26)

**Comment by roycejam7** [comment]
I'm having this issue on 
* macOS 14.2.1
* Burp Suite Professional v2023.11.1.5
* NoPE.1.8.2
* M2 Pro

Steps I followed:
* Install libpcap with Homebrew
* install NoPE extension
* select interface in Server Config and specify port 53
* press green Play on Server Config
* set remote device DNS
* DNS traffic appears on NoPE Proxy "DNS History" tab
* on the DNS History tab, press green play button under Port Monitor

Nothing is displayed in the Port Monitoring section

I'm able to "Add 80 & 443 to Burp" and install Burp's certificate to middle-man HTTPS traffic
