### ISSUE TITLE
Location burpca.p12 certificate store on mac.

### ISSUE THREAD

**Issue by yayip** [summitt/Burp-Non-HTTP-Extension#51]
Hi, 

I'm trying intercepting SSL traffic with NoPE, but i dont know location for store p12 ca certificate on mac. 

Thankyou.

**Comment by yayip** [comment]
I solved that, location at ~/.NoPEProxy/

**Comment by YSaxon** [comment]
For future reference, what worked for me was putting it in `/Applications/Burp Suite Professional.app/Contents/Resources/app`, ie in the same folder _within_ the .app as `burpsuite_pro.jar`
