### ISSUE TITLE
Not working? What am i doing wrong?

### ISSUE THREAD

**Issue by ifoverload** [summitt/Burp-Non-HTTP-Extension#54]
I'm trying to get this work on my android device by following [this](https://medium.com/@juan.tirtayana/intercepting-non-http-request-using-burp-suite-extension-8c264b3c41d1) tutorial.
i follow every step on it, but i dont see any content on "DNS History" tab.
Im currently using burpsuite 1.7.32 with jre1.8.0_162
any clue?

**Comment by summitt** [comment]
You need to run with admin privileges since it opens lower level ports. The newest releases fixes a bunch of bugs as well
