### ISSUE TITLE
Proxy can't be enabled

### ISSUE THREAD

**Issue by molitona** [summitt/Burp-Non-HTTP-Extension#55]
I'm following FB guide to configure FB Lite app to be proxied through burp (https://www.facebook.com/whitehat/education/testing-guides)

I've a problem that is the proxy can't be enabled even though burp isn't listening on port 443.

![2021-09-03_15-09](https://user-images.githubusercontent.com/35532337/132019262-5fd9c71b-862d-42b3-aefa-035cd9b88d5f.png)

Any help, please !

**Comment by rbk0** [comment]
You running Burp with administrative privileges? If you're using *NIX start Burp as root. If you're on Windows running Burp "run as Administrator" should solve the problem. Listening on ports lower than 1024 requires administrative privileges in general.
