### ISSUE TITLE
SSL feature of NoPE

### ISSUE THREAD

**Issue by akanksha217** [summitt/Burp-Non-HTTP-Extension#64]
Hey Josh, I have been trying to capture FTPS (FTP - SSL) traffic via NoPE. 
I can successfully intercept the encrypted traffic as long as the SSL button is not enabled. 
But as soon as I try intercepting it with SSL enabled (in order to capture SSL-based traffic), the communication stops midway. (PFA)
I've followed all the steps right from enabling SSL before adding a proxy listener to saving Burp's CA PKCS#12 file at the location where Burp is installed. (PFA)
Not sure what I'm missing out here!
Any kind of assistance would be appreciated!

![image](https://github.com/summitt/Burp-Non-HTTP-Extension/assets/73606186/5571f023-ea1a-439c-abad-47f1434c7b6d)
![image](https://github.com/summitt/Burp-Non-HTTP-Extension/assets/73606186/11c635c2-f10c-4fc1-862e-4340241beeab)
![image](https://github.com/summitt/Burp-Non-HTTP-Extension/assets/73606186/f9b9ed5f-a71f-463a-8701-23eeb3f00ce3)

**Comment by iamat8080** [comment]
yes am also having an issue with TCP SSL can anyone help with this

**Comment by summitt** [comment]
I just released a new version of NoPE that fixes many issues with ssl and DNS handling as well. Try it out and see if this fixes your problem. 
https://github.com/summitt/Burp-Non-HTTP-Extension/releases/tag/v1.7
