### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by securisec** [summitt/Burp-Non-HTTP-Extension#7]
Would you please be able to provide a bit more guidance on how to set this up in burp? I tried installing the java file in the burp folder through burp extender, but that fails

**Comment by summitt** [comment]
Did you download the jar file from here: https://github.com/summitt/Burp-Non-HTTP-Extension/releases

**Comment by securisec** [comment]
That fixed it Josh. I cloned it initially. Thanks!
