### ISSUE TITLE
Could not compile it 

### ISSUE THREAD

**Issue by 444kx** [summitt/Burp-Non-HTTP-Extension#8]
Hello, 

the code is not compiling successful on maven / kali OS by default. 
I think the pom.xml is missing json simple and jython depedency. 

Also if you want to add the extension to Burp, it needs to be in jar format right ? the Burpextender class has no void public main function. What am I missing here to compile it ? 

Thanks

**Comment by summitt** [comment]
you need to go to the releases section to download the jar file. there is a
link on the readme page.
https://github.com/summitt/Burp-Non-HTTP-Extension/releases

**Comment by 444kx** [comment]
omg thx xD

**Comment by summitt** [comment]
np ;)
