### ISSUE TITLE
Cannot start DNS server

### ISSUE THREAD

**Issue by AlucardNosferatu** [summitt/Burp-Non-HTTP-Extension#80]
<html>
<body>

1725360598580 | Info | Extensions | Non HTTP Proxy (NoPE): DNSMiTM: DNS Server Started.
-- | -- | -- | --
1725360595963 | Info | Extensions | Non HTTP Proxy (NoPE): DNSMiTM: DNS is Shutting Down
1725360595963 | Info | Extensions | Non HTTP Proxy (NoPE): DNSMiTM: DNS Server Stopped.

</body>
</html>

win10 x64 BurpSuite v2024.8 OpenJDK 21.0.3.9 (Microsoft)

I start dns server, but no port open on my pc, neither high number (53000) nor low number (53)

**Comment by Scrooge20291224** [comment]
Burp doesn't support wifi

**Comment by Pordrack** [comment]
Hello, it support Wifi, it worked on wifi on my computer. I just had to be sure to setup the DNS on my Wifi interface: 

<img width="1149" height="294" alt="Image" src="https://github.com/user-attachments/assets/94e8d4b9-f0bb-49d2-ba49-928f3ecba340" />

And to pick the right interface: 

<img width="1260" height="472" alt="Image" src="https://github.com/user-attachments/assets/6d3c7847-8613-4a87-ab83-0983b66cbf91" />
